name: Deploy AWS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate config.js
        run: |
          echo "export default { 
            PROFILE: 'prod',
            BASE_PATH: '',
            API_BASE_URL: '${{ secrets.DEV_API_BASE_URL }}',
            KAKAO_SDK_KEY: '${{ secrets.KAKAO_SDK_KEY }}'
          };" > frontend/js/config.js

      # EC2로 정적 파일 배포
      - name: Upload static files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEV_REMOTE_IP }}
          username: ${{ secrets.DEV_REMOTE_USER }}
          key: ${{ secrets.DEV_REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.DEV_REMOTE_SSH_PORT }}
          source: "./frontend/*"
          target: "/home/ubuntu/deploy/tmp"
          rm: true
          strip_components: 1

      # Nginx reload
      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEV_REMOTE_IP }}
          username: ${{ secrets.DEV_REMOTE_USER }}
          key: ${{ secrets.DEV_REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.DEV_REMOTE_SSH_PORT }}
          script: |
            # 기존 서비스 디렉토리 제거
            sudo rm -rf /home/ubuntu/deploy/today-book-front
      
            # tmp → 실제 디렉토리로 이동
            sudo mv /home/ubuntu/deploy/tmp /home/ubuntu/deploy/today-book-front
      
            # nginx가 읽을 수 있도록 권한만 정리
            sudo chown -R ubuntu:www-data /home/ubuntu/deploy/today-book-front
            sudo chmod -R 755 /home/ubuntu/deploy/today-book-front
            sudo systemctl reload nginx
